//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soundpad.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAKzmlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJ" +
            "jZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIiB" +
            "4bXA6Q3JlYXRlRGF0ZT0iMjAxOS0wNS0xM1QyMzo1MTo1OC0wNzowMCIgeG1wOk1vZGlmeURhdGU9IjI" +
            "wMTktMDUtMTZUMDA6MjA6MjEtMDc6MDAiIHhtcDpNZXRhZGF0YURhdGU9IjIwMTktMDUtMTZUMDA6MjA" +
            "6MjEtMDc6MDAiIGRjOmZvcm1hdD0iaW1hZ2UvcG5nIiBwaG90b3Nob3A6Q29sb3JNb2RlPSIzIiBwaG9" +
            "0b3Nob3A6SUNDUHJvZmlsZT0ic1JHQiBJRUM2MTk2Ni0yLjEiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5" +
            "paWQ6Y2M3MWZkYTUtNGEzMi1kZDQ1LThiZDMtZmY3MjBiOGVjMmJjIiB4bXBNTTpEb2N1bWVudElEPSJ" +
            "hZG9iZTpkb2NpZDpwaG90b3Nob3A6NGVjNTA4NjItMjFmYS05ODRiLTk5ZjAtYTVlNmM2YjI2MGNlIiB" +
            "4bXBNTTpPcmlnaW5hbERvY3VtZW50SUQ9InhtcC5kaWQ6YjI3YmIzMTAtNmIyMy1kMzRjLWI5YTEtOTg" +
            "yZjliZTk4OWYwIj4gPHBob3Rvc2hvcDpUZXh0TGF5ZXJzPiA8cmRmOkJhZz4gPHJkZjpsaSBwaG90b3N" +
            "ob3A6TGF5ZXJOYW1lPSJTb3VuZHBhZCBOb3QiIHBob3Rvc2hvcDpMYXllclRleHQ9IlNvdW5kcGFkIE5" +
            "vdCIvPiA8cmRmOmxpIHBob3Rvc2hvcDpMYXllck5hbWU9IlJ1bm5pbmciIHBob3Rvc2hvcDpMYXllclR" +
            "leHQ9IlJ1bm5pbmciLz4gPC9yZGY6QmFnPiA8L3Bob3Rvc2hvcDpUZXh0TGF5ZXJzPiA8eG1wTU06SGl" +
            "zdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJjcmVhdGVkIiBzdEV2dDppbnN0YW5" +
            "jZUlEPSJ4bXAuaWlkOmIyN2JiMzEwLTZiMjMtZDM0Yy1iOWExLTk4MmY5YmU5ODlmMCIgc3RFdnQ6d2h" +
            "lbj0iMjAxOS0wNS0xM1QyMzo1MTo1OC0wNzowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGh" +
            "vdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIi8+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJjb252ZXJ0ZWQ" +
            "iIHN0RXZ0OnBhcmFtZXRlcnM9ImZyb20gaW1hZ2UvcG5nIHRvIGFwcGxpY2F0aW9uL3ZuZC5hZG9iZS5" +
            "waG90b3Nob3AiLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249InNhdmVkIiBzdEV2dDppbnN0YW5jZUlEPSJ" +
            "4bXAuaWlkOmM0MGZlMjU5LTk3NmQtNTE0OS1iYjczLWNjYzJiOTk4OGNkYSIgc3RFdnQ6d2hlbj0iMjA" +
            "xOS0wNS0xNlQwMDoxMTo0OC0wNzowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9" +
            "wIENDIDIwMTkgKFdpbmRvd3MpIiBzdEV2dDpjaGFuZ2VkPSIvIi8+IDxyZGY6bGkgc3RFdnQ6YWN0aW9" +
            "uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDo1ODNiOGM4MC03YzY0LWNkNGEtODRkOS0" +
            "xOTBlYTJhZDljYTEiIHN0RXZ0OndoZW49IjIwMTktMDUtMTZUMDA6MjA6MjEtMDc6MDAiIHN0RXZ0OnN" +
            "vZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIgc3RFdnQ6Y2hhbmd" +
            "lZD0iLyIvPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY29udmVydGVkIiBzdEV2dDpwYXJhbWV0ZXJzPSJ" +
            "mcm9tIGFwcGxpY2F0aW9uL3ZuZC5hZG9iZS5waG90b3Nob3AgdG8gaW1hZ2UvcG5nIi8+IDxyZGY6bGk" +
            "gc3RFdnQ6YWN0aW9uPSJkZXJpdmVkIiBzdEV2dDpwYXJhbWV0ZXJzPSJjb252ZXJ0ZWQgZnJvbSBhcHB" +
            "saWNhdGlvbi92bmQuYWRvYmUucGhvdG9zaG9wIHRvIGltYWdlL3BuZyIvPiA8cmRmOmxpIHN0RXZ0OmF" +
            "jdGlvbj0ic2F2ZWQiIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6Y2M3MWZkYTUtNGEzMi1kZDQ1LTh" +
            "iZDMtZmY3MjBiOGVjMmJjIiBzdEV2dDp3aGVuPSIyMDE5LTA1LTE2VDAwOjIwOjIxLTA3OjAwIiBzdEV" +
            "2dDpzb2Z0d2FyZUFnZW50PSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHN0RXZ0OmN" +
            "oYW5nZWQ9Ii8iLz4gPC9yZGY6U2VxPiA8L3htcE1NOkhpc3Rvcnk+IDx4bXBNTTpEZXJpdmVkRnJvbSB" +
            "zdFJlZjppbnN0YW5jZUlEPSJ4bXAuaWlkOjU4M2I4YzgwLTdjNjQtY2Q0YS04NGQ5LTE5MGVhMmFkOWN" +
            "hMSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDpiMjdiYjMxMC02YjIzLWQzNGMtYjlhMS05ODJmOWJ" +
            "lOTg5ZjAiIHN0UmVmOm9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpiMjdiYjMxMC02YjIzLWQzNGM" +
            "tYjlhMS05ODJmOWJlOTg5ZjAiLz4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1" +
            "ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz4TNraVAAAlk0lEQVR4nO2deXxdVdX3v+vem6RNmjbpDB0oKZQ" +
            "WSoG2ig/CA2r1QUFEBQdAEJACD4ID+FZUHpFXpBVUBAdaBxwYqzKLaPFhRoGCQClIaUvngSZp0qQZ793" +
            "r+WOfk5x7cm9yz3CTFPrL53ySnLPPPnvv8zt7r7X22muLqhIJItHu7wNu6cT5u7ff+M7hOw8kBZJASqF" +
            "aYLLCZIFJwARgLDASGAMMA8qBMqAdaAGagB1APfAWsAnYoLBB7O9GgYxCBsj4y+QvX9BzQdMWjAgcSIW" +
            "+c8+AAEOwZDgEOByYC8xySFMVB/2dPHYKrAdeBpYDLwCrsKRri+ExgxLyNu2BhikMB44Q+BDwMWC/ohY" +
            "0N94E7lH4m8AKoFGh+e3UA72dCJQCxivMFfgw9phU1MIFwwbgIYUHBZ5X2CaQhr0EinZ/HyiAQEMVJgk" +
            "cD5wDHFbUAsWDFxVuFngQ2KzQupdARUIvBCpXO0SdAJzGwAxRUfEG8AeFuwVWukSCvQSKDXkIdARwusA" +
            "XgBFFLUD/YAfwK4XbHFlpL4Higo9AhwAnOcSpKeqDBwavAr8G7lN4Yy+BYoBTulKBTyt8SWBOUR84OPC" +
            "Uwo0Cf1SPPQn2Eigw1ArFFwl8FmvPeadgF3Czwi+AlWFU/oLxNibQWcCXsQbAdyqWK1wncCfsJVChqAI" +
            "uAy5y/n6noxb4KXBdoYbIQHibEegg4EZgHiHbIwQywHa1Uw9bsMNHi0An1tiXUigBKrAW7oliyzkaSPR" +
            "TGdPAXxQuEVi3l0C58V7geux8VTGx1iArO0is301JWxNlyRZS1S2kRnWQGJlBKjPIUAPJDGpw3o9gdid" +
            "gVymmrpz0znI6d1bTYYaTLi/FTEmiM4D9i1z2p4CvKjy7l0DZ+CzwXYqnnj/SSeLpRobsqGPoyBZKDmg" +
            "jOSNDcqZBS9TR99RzGMCgnnOCm84Aan8ySXixjPRrlaRX70tb41jax5dh/gP4zyLV5U2FLwvc55b5nU6" +
            "gU7DD1vg4MvPgLQN3NzHk6c1UjWohdWQGfa8hMdESRBxiKIURqNsuZZzUxpPWwSbBPF5Fx7PT2d0wjvb" +
            "3CnwCGBVz3bYD5wP3vtMJNB/4DvGS5yWD/Go7lat2UDGnndTxkDjGoF2EALpevksiiIVAZGyKtIHHh5J" +
            "5cCqtL02neUbCGkBnxVjPOuCLCne8Uwl0KnAD8ZFno8LVW6h6rpaKYzMkTlUS/+ESxHheOBSPQN7nKJp" +
            "W5PEUmTsOpOXJWTS/X+DrwMSY6rxL4bMCD77TCHQa8APiIc9bwM93U/rbtYydk0bOBvlgBilxE+QmUNc" +
            "QllG0Geuv02CgEWgzkDaoCEYzJJIKFYpWgIw0UKVohULSeAYQ4wyH2eQEYJeBh0rQX5/CttcEzgUuIR4" +
            "zRQNwmsJf3ikEOgr4HTA12sPJKPwduPR19m1uJ3WeImcpTAAl43Futb2EeoRfaQW2KLyu6AvGOn9tMbD" +
            "DoLtBOgxkFBUho8YSqEwxQw3JccAEg+4POssgByk6ARLl+QjktrLCasUsriB9y8eo20fgOuBYrKttFGx" +
            "W+IDA64Hv3MMINA24BXhXtAezXeF7wJKVTDpUkW8ZEh9WTIlbo4wnsUsghQ2K/ssgfwd9Ua1NZfsxbOr" +
            "wt4R/Dsp/7QH2LVN0jMLkDBwOciwwx6BTeyEQBm1V9F6Fq85k+5vAV4EFWBtTFDwLfBLrq1049iACVQJ" +
            "/Aj4Y7aEAfEfhO68y+aOGxJWKHtGtUVn4CLTWYO5X9EFFXjbIW0ex0UC2Qc6LvgjkPXcP+wjIaGB6BnM" +
            "SyIcVDvESyc3H7QmBJwx6xefZ/hhwJNbaPJuQooyDh4CPE8QPew8hUBnwbawAGYfu39RA+d2bGf0+g0z" +
            "yCsPdBBLA7AJ+q3C7QVe8m03NfsLEQSDvuT8xvhzkYEVPUTjbIGNzEcgp8yqFb57Ntj8q7CfWnPEhbHu" +
            "FQQdwNfA9dVxm+4IMJIG0QAIJnAn8mBjnthTRrVRLPcN8Nh33Og8r5keKPDaXjbvzESZuArl//4HxQxU" +
            "9yiCXKXK8m4+PQABbFb5uML8/l7dSwDXYecAhhbRDDrQAZyn8sZDEewKBDhG4HTg00sNyPR9hC9XUU9m" +
            "lShu0QcncCHrDEWyp9d+Ti0CPMaFEMCMyJCcDYwxUKpQqKs7Lble0UWGHIlsVdp7A5g5/vur7W4A7GD9" +
            "J4RyQSxRG5iAQCrUGc5mit3yBHSXY3vq/CS8Xvap2PnFrXwkHO4GGAj8R6/BeFLgkqmU4inlNyXxbkbu" +
            "PYFPeLvyf7CsGGQkcaOBog8wW9ACDjFdLnoQB8diBVK3Wtwtr4V4j6LMGfVKRVQbddTJbNReBFLiD8WX" +
            "ARwx8R5FDXRuSS3rHllSrZL5s0NvnU2uA/wf8D3YSN3izwG8UziNbHOyBwU6g0wV+QpHdMhRhGyNWv8X" +
            "w02ax4bl86f7BxCToREGPVRIfyyDHKVQrKjafIIZEMOhO4FGD/sGgTyiy5RNsNX4CubiN8XPVumUcYyD" +
            "hlY0c9X+TIXMhyJ/nsyOJ7YkuI9xwtlOt9fuu3hINZgIdiF1xcEikhxSOdoWvAD/PdfFZJo7NwEeAs5T" +
            "EcZpFDtsOwQikHiKBQR9X+KVilp3C9m25CARwK+MPUPiBgRPUsf+4spHz9wqDOW8+O57BCtPfA74IlIZ" +
            "okxcUTqSXoWywEigFfE1s5fsTHQ6JfuaeWM7EUkWOVfSCDPJxHDEo3qkMtx1MxmDuNcgSRR75FFt72Jc" +
            "AbmXcJEWuz8DJOD1RN4EEg/5NSJ97HnWbsL33L7CTzoHbA7gKuDrfm45CoMjOUJL/OFjs+NvfKBVYJHA" +
            "BwAtMHIV1i/0NyCekaE5qLr0kCYlPgPwSuGgp46pzpT6D7RsFvUzgr7nzkw8pyW/exOgh2KmKK4BnQhS" +
            "sFDttND3EvX0iMoH8X6dzlGP9mcM4V9Vj1djdEYo1DLi2nZIrQa4FWQiyb4T8wmAi6ELge0sZn3Pi9HS" +
            "2vynIAoV/Zl+xrWhInAVyunPy38DXsO6tQXEw1vUjdhTLHfMw4PNhblS4EviWMwx19JG8NwwrJf3NMTS" +
            "fLUiR147kg5RC4gLgR3cyPue835lsXQFcDqzNutP+GqokLruJMUc4p5/AWqs7QxTmZIk+fdQDxSDQELF" +
            "C28igNyosA5YAZh37395A1QqNMOIk0NQEGhlLU+g8osL2JXKKkrj+dsb38LZU4PNse9Sg1wiSZSUXlAQ" +
            "yXZEv/YxR5U7v/mMskYJiCjZKSawoBoEmYoevoKgX+IrYYE4IfKKe6lm1jCQKiZIYJtDIGJpD5xEP9EQ" +
            "hcd1teYYzkFuAO+ihtCkgHxc7vwWwEzsdtCNEIY7HasaxIW4ClYot5IQQ994IrARYz/4TFL4ElDRRyY4" +
            "YSDSRBsYNMIkMerIiV97O2BH+a+ewrU3R7yr6TE85X4cryQt/xpj9nBPPYW07Bc11eTCLbiLGgrgJNBp" +
            "H+wmIzQpLuvQY9Aw8rp9NDHNJFFrfTGGYSOOAksjRAD+n8NXbGN3D/+cctq8Hs4jcgvKRinwauhSVhVi" +
            "/6CAoEfgvYHLA+/IibjV+LlbiDwRHcN4KsIkpkw3yKTzh9xRhF8NoYPg/CCdAApZEk2lk/ACRyGmjUkP" +
            "ivw3Jz+ZKo/CAkrmNntMPKYEzfspo98Nah5WHgioaxxBjfIE41fhh2Fg9Qceal4H7nWxQ+Bw5SKjIK40" +
            "M/4ajnYVW8QcJiUYrcuktjJ3tv34utWnB3Czomhx3z1TkpJ8wKgWgsJigzmN2geR/OL8jI84hrApLoEB" +
            "QuAmny97ElImKnCA95306BO5Nk3ocm/4yCM8Al0T7DACJusdgOVyR+b9lfFWONK8o5vcgad95ETg5gUx" +
            "zTu0CbiWgLCR2vVos6+/iJNBMggvPdQLLxAlhIshJTj4+yAohcftU3lTsjPhirO2kMWxhUximOCQaGBu" +
            "RYkh+SpHjf8M+4hUFzqMuLehSMK96lQe7rDExS5H3/YzRCefKLVj/nyCYDRwQRy3ikoGGiJ2kDASFpTi" +
            "C4Gb2HwrME+tK4U2zW+CuGtau9J5W+EkHqWsNiaCaSBeSGPangfH9SCKvnSeBqRb0AsVM8ac7j7pVYie" +
            "F23z3lyjyUYVxzqlVwN8CFqME68gf1uuxC3HFiR5OcCNVp1gCNQEoHKs5hDuBbQZ9YTVTJqn1qU5nkN1" +
            "CulnImBG06hgaSWatzCocSZSpNKDANsojmQuCwtE4jwb55M2M/6VBK7AhipMG0op5WTCrFZmZ5XqGvkt" +
            "tyBt3hv2n2EnZgt+nwHFqo9iujlKHyARyqjVdgquGT6QpWb2dSYcreqjC6Zp7CKzGDlcG+8V0ClqnJOs" +
            "NyeNqKS3JIIyjgVRIEiVQDqABQdjC0H4mkSQF+SLowVjrfRV2AtRYGUjG+G2Lah3hvvljxtQYeOY4ml8" +
            "4gtY12IghhcIVOSIRKA53jhRwscAPg9yXJnVtLRPaDMkTFJ2db8Wo12Wi283CNfR3XxtJUyQSuXiDUWy" +
            "mgozzlOgrU3u4rubyifb7A/kWQPYsg8fl5BUw98ynfnIF5swgdVXrbPbrKCSI3AM5xrGg4VhMMyM/YEj" +
            "MDk/f7DvrqESBfWgIPZwBTKWODBm2MoIMSh/eoIMBMxWZ+QQVrxwffM7vYKzLcVAhvAtx2IFKCBgwIEM" +
            "q3UnZ7Nz+euFRRyVbqSIToVoJYBoNjGMrSoYEJUjkRaPFhG2/DZTO7EQCfTmOz1ZOf6VCEYcaX03ALQX" +
            "SlJVqkTxJahnGlhhINJ0OxrCZVragdJKkhMQgJlIbQi2poJWeilVMQiMONX4yAYN9pynFFDEyXFwkmpV" +
            "MMqUiRTNbaWUz0EmCEorm1BgBBmF7cIlkMiHcbryIYwgLPDGXJkWxX0Itw9hEVSSiJjIZZnameddRR5H" +
            "cZyRNbKWdbYCSoCTGwTc6FKgN3kOWacToKHEI0QEJJJh+2qZsB8MAYRL1JEK+bunoYPJLLzHy3C+wqqW" +
            "NLQ/ez+4tm0kyjDJGoCTJkCFOWS4MFNgZboiN5OobxzgSKFCSIUGx5J9c2EElGxgeTbnfvZthN/+aww6" +
            "ewbt/dys1519Ecmwlu2Qb7dQjJEg4H8VA0qiBJB3Be/axUZ4Zx5scHSRxmhJMPwujb1HBGhJhYxlZNDW" +
            "RvOpKxq56jcN+sIijbr2VaefPRyaMoDm1lQ4aERIIiX41RHrRToJdwds2kgwUx1gSSA00pAakgbchjHj" +
            "XUYx98VnoCOmr39AA3/wmqUSCMeefz+hj3suUsz7P+ttvY93999G8cTMl6SEkGIr9NuM1U/QFBVoDtq1" +
            "EXDEcRw80ru8k3dAB/EJ3HXQImYWLIBXhu9m5E77xDfj5z5GyUka9593M/vH1vP/u+5jxxS9SOm08Hcl" +
            "GOtmFoR3rDtc/9VWgLfgrrYryzDgIFGgDFO1yWuh/qCTQM86AH/4QSsOsEnZQXw9XXAE33dR1quqwmcz" +
            "50Q94/x/+xIyvfpmKw2roLG2hnQYydp2AQ6Ti1j2EDBRpRj4OApUHSy4Dq6+UlMD558ONN8KQsOF3gLo" +
            "6+Na3skgEMGLWTGZ//xr+87e3MPNblzNi7iw6S9tppZ5OWrCRG5NF6ZVCTrxE+JLikYEiFWBAUFoKZ58" +
            "NxsBXvgJtIXflrquDyy+H9nb40peyLlUfNovqw2Yx5WMns/6B+3nznnupf/FlMp0NpCgnRQVCiu5V+fH" +
            "ABCdmJA7EQaD2oDf0r2iZByUl8IUvQCIBl10GTSEXHzY0wJVXQlkZXNBzQUr1rEOpnnUok048kXX33cf" +
            "6Bx6g/tWVaEuaRCYVazsIhLF3hV6kAPEQKOBM7oBTpxupFJx7LnR22p4kCom+9jWr3V18cU5zwahZsxh" +
            "58CFMO+NzbHnsUV698SZqn3+RFCMQEsTVLiEMJJEIFIcMFMgz3Y1kOGiQTMJFF8H3vw9VVeHzaW62MtG" +
            "SJZDO7WUrqSSp8qFoxpDpsO8tbkmoLHjbhhy/LeLogd4Kkli6wmEOMlxwAWQyVrvauTNcHk1NVqbq6LD" +
            "5lXSvnGlet5F199/PG3fcQv3rr5NsNJQxEu9GL1EhQFlAm7tCYxQSx0GgQK2dII1giB6YvQi46CLbI11" +
            "xBdSGiaICtLba4aykBM49l7a6et685x5WL72T2uefI7OrhSQVJBjq9MXxfUwJoDwggSTg+/Oj33ugFJ0" +
            "OgQYpLrjArvm44gqrZYVBezt8+ctse/JpXtqxne3PPoNpaCFFOaWMA4RMVojNeFCG8cSqLQxqg1qERhw" +
            "ECrQyMoEhMZgJBHDhhfZ3RBKNu/X3DJcS6rSCBKOwtVdMkepfTYbS4D1a0PX1WYhDiN4QLLmSCBxUYgB" +
            "w4YVw9dWRBGsBjtQ005xVYPFafLKRwBIoBLZEfW5UbCCgWmWHsUEoSPtx/vlw1VVQHd5tOIEym0ZqIkX" +
            "s6xsCjA7+YbbJIOiB1hNwiXGKjsEtB3lx8cWwcCEMCzTll4UEMIddHBB+8UOfEJRxwQm0DrvrYWjE4dL" +
            "aiCVRwSihwwx6OciL+fPtcFYZ3v88iTK7iCQaijKKTNBufQ1Ei/8Xh1N9BhuiJcBD04kUnZGY39/o/Ny" +
            "ZNJ5xOiYZ3vzgkujAIpBoAp21KSfafqFQeE1tCOHQiGMIy6gNuRYI5TT8NYE+ArQOZmko3dTM9vsf5MV" +
            "LLuGx++/mxUwm0lLDFMocmpgWH4lagb8eSUvgd4ANKdga5eFxrI03wPKg95XSNqWCXZc0MWIO6AeAg9W" +
            "6x5aQ30CSwbqPVFJkx5rM7jbqn3iMDbfeyrZH/5e2TZtJMIStTKCUNg6O4KifQplNEwq83tMbpgn7UrM" +
            "DttoAFlm+OwodoIvHkV48ivQDAYuxGzuERUIcdiDFLtDfQLAVGnMrqRtRSd2SLex/r1rn/HF0BRbIiRZ" +
            "BagQuM+iBxei5TEsbtU88zpY772D735fRsmETScooZxwJhmBQNjAEZQQzaQytTZaizKGZBPCasxmPoqs" +
            "E/aEgG+l+N20CkxS9AmQ/936HXRsVbjmdhn0JHjBqpURU4SGeZT1gI2Xdhd1SoFCUKnwaeGYf3txOger" +
            "kKqYMBT1aIF4CdWaoe+RRhzgP0bJ+EwnKqGA8QgkGwZDpsuVsoAIFZtIYuicqxXAEzRiEf1OOYJaB/O4" +
            "ctmcNKzcx5miQrC2fnCe+Kcg27DYIQeWfvwMbCXqjD3HFSOxQeDDovQKfIeDCtmmsa4XE41jSxoKdjzz" +
            "OyosvYcV557H5tzeTWV/LUMYzhHEOeRT1rf1SYCPlvBJxyVAphtk0cTDNnYI8fQ5vZZFnCaOHCvJhYFS" +
            "O21ecxs5RwPsDPrYDeIpoOwEA8QWYUuBVgg9jw4HjxUanD+CXos+ArgE5ou+04H5jmsmA6SbBrmdeYOu" +
            "dt7Lj3vtp3bAF0lDGaNw57e4NvPOUAthAOQocyq7QPVEZhtk0y0G05hiGZLQix2hPDWu3oC+PJf1ZAm5" +
            "Ip/ACNrJZZMQ1hIFVB/9CwE09xG7reBuBZoV1JXaXm0MpqA4GJUPJyBEkK8rZ/dq/2fKLX7HjoQdpfWM" +
            "9ki4lxXASJFEEdRxDC6GDQbpINCsCiUrQVBXprwB16tnvzMChThQNT85CAv49ifaVYjekCzqSPAm8Gaq" +
            "gPsQZ5rdF4c8hspiBHcoKJvN01hvgz6DrCi1hkhGktzWw6dobeOUzp7H5+hvofG0LpekqUlR2rSwN4+x" +
            "mENZTzssMd3aKDo2RwNXiBGv/JaMrBTlRfcOXrZFZ/mF2nUjwwKZt2OErlgnJOBepK/Ai8BJ2t55CIdi" +
            "v6H4CzOwr+k9BHgIu1F6di5QEpZTKUGrvfYDOu3ch6RJKGesss3aLHk0kNwjrnJFkJruI4O1cDVwjkBB" +
            "4SuB9PQdRbTiQ9ldK0a8TMN6z2o1aXghbOD/ijlS/BfhliGzGAecpJPOFcvMfM9iYBu7UAmP8qRqkI0F" +
            "JuookldDlhxyfLqfAOipYwXA6ozVtFbDwKHZ/FxLT/X2awMvH0fQeAi7qBIzAXwU2eN9bFMQd5SADPIR" +
            "v76sC8SUC7q06gw1PJjB3gfSpTQjqOK+7VS6O/VuBtZSzgko6ojVv5TTaPjKDFp9cJWYmLSuGoB8i4Ai" +
            "i8E+1PX1sKEaYjM1YoTgoRghc78Sc9vds5Ppi7P9mMZjn+m8BcWFYQzkrGRapJ0qhiffSxHRau3Ipwax" +
            "9L7uPBMYEzM4I/C+wyt+bR0ExtrxsVbiXcL6278PuhVEwprN5fYr09SA7XZv/YMEbVPBSxJ4oiXI0zRx" +
            "EKyXAB9jVWIoGkTFdrMK+l1hRrEA9r2L3tAiDb2BD8RcMQe9K0bnYdG/DPmiwhnJeYVhkEr2H3RxN0+7" +
            "96ZhM8I1S0sADGmLOsi8Ui0AtCr8jXBDrYVhBvGCD5HS2miTp6xKYB7QrrMrgwSqnJ2qP0NxDMRxMa0U" +
            "SDTp0gdWOwyg3faKYocL+jWfv9oA4wrl3eKE3TGdbXQK9QmxjDTqsppyXqaTTtwNPP6ADu6PP633JlGF" +
            "Q7FhzdxPCV8jBR4D/IUAY2plseAkyXwXzejzNEy9WU/6vBkquI6ITV0D8Q+1erEVBUQmksE7t1oz1IW4" +
            "X4FLsPhkBmKCPgrkUeCPEM4uJlxQuHk3H5Vg5rz+2km4ArgW29WZTi4L+iHb5ILYLDYvLsEQqSHA8jE0" +
            "K+hcwF4NZEeG5MUIfBz3ns2x9CsCZ61pAhE3zCkAG+H3I6aWCEcdmK4UkmypWhQxkKPSgHfslfRdod0v" +
            "sTjD6XfcU+BeTRNF3Q+IaRY5VSBhnSZ97f/aGKNmTGupcj7bZinYq3KHINYq2K3KwQrmiYqDxE+yYNYz" +
            "MVcSwb1cOvKhwEo7PT2+QCBzoLwIhcAr2ywsU1dWDNHAD8G11vtzeCOT+foGJUxT9mpI6w8Bw07UnTtE" +
            "JtA30BoXnDHKS2t2SRymIsQRKA2sOYff4w2mekozXMt4InKYF+mjtKQRKYoXiywm/4asB/qTwLWBVIQQ" +
            "SYDkTSpXkpw16qYHp6nzxxSCQQruBp8DcYGCMIpeqfWZX/v7tng6kldk0MTSepU4KfA34QaFvdkAJFDD" +
            "2cjXWPnRitIfyNHYG/+FCCOTW8FkmHmjQM5XEJ4EpBobGSKBW0A2K3KrozYp+3CDfUaj23peLQADvYRf" +
            "T41mpcRdwBgFWu+xJBAJrILwDu/V0FGwEfqPwPXGCJPVFIPfvfzDhMJATFfmwgRqFcYom3DwCEMgYG53" +
            "kdUX/ZtD7TmbbK3exzxkGfqIwwn+fn0BJlMNoZgptVEbfm+xRLHk2B7prDyMQ2L1R7yHgNgk50AY8Blw" +
            "FPF0ogVw8zcRJCnMNcrSihwD7WDJRpVCWg0DtalXjtwxsVPRVRZ8U5IWPsmWjAnez70GKLjUwKxfxvAQ" +
            "aRwezaGYcnaE9GT3YqPABCWO+2AMJBPBR4FcEn1XOhW3A3Qo/EFhTKIHc/59gUgJ0pKL7GZgEMl6hykC" +
            "ZQ6CEoq2KNCi6XZH1im44gS21bj4Ad7OPKHKRoosMlOcj0DA6OYgWJtMWl9xTB5yi8Giot7GHEiiBlYV" +
            "+T4Api16Qxi4N+rHCLwV2Fkog9+8g8OcD8Cf2rRDkZ4p+zqDiJ1Aphqm0MI0WhkZ1fu1Gs8LJAn/3yoO" +
            "BEIED/bdtTk8Y4AGs/29jDPmlsP7B/1/gGeywNj2GfIOgEnQffCsoKkkziyb+i1pm0Ux5fORpAk4DHok" +
            "nu+Don4278sNg3VIbxVqrq2LIsww4ELhcrJfjQ8Bi4J9YmaloYUHEfpBJwS5fHkUHNbQwjvZibDFTp/A" +
            "Zx0lswEKdDOQQ1gWnBB8R+6KjCta5kMY6VD2s9mt9HqgVGxgig/XWC9QQTmLBOr8ngdQmhhxQy5BfVNL" +
            "57nG0U0G6GNO5CqxXOBtH5vHLfMFz3DNloC54SjBdrJ1oLsWdSm/CRqZ4QeEV4A1He2nE1d6zt253y+I" +
            "6VSfULsGZBhwoMBPrBDeDgIv8AsIAjyp8EXjNLdheAmX/O1GsN+P7sXua9xeasIGyarHuuE3YObg01nJ" +
            "eit1cuAq7y99kiksWP1qAhxQuwmqdwF4CAT3HDrHtcAVWhom0o97bBLXAdcC16pN39hKInARy8Wms78y" +
            "syA/ZM2GAfwFXYjXWnG21l0D+LLOvTRI7CXsSETeI3cOwDfijWheW7d75Pi/2Eog+CeQ2zqliHcvexcD" +
            "ar4qNDuxk8fXqWYazl0C9oEACAewjcC7wSeDwyA8efHgWuBP4nVozQw81cC+BciAAgdxrhwLnYB3vp0U" +
            "uwMBjJdbguQQnbk+eeu8lUC6EIJB7/ijgBKzK/57IBel/PI0NNXe/wnOF1tuLvQQiEoHc3zMUPirwQeA" +
            "YiuNjHBfaFB7HBsj6M856Lf/L30ugAIiBQO7v/dTKRscIHI21Dod1n40TabXyzT8EHlermnc5u+/JBEJ" +
            "Vcx9wqsJStdm7x3KFBb50g+4wkFI4yMBHDFynNqxJq68uxT6aFf5p4Bq15ZjmlMtf3hrPPWv6qFuN7xk" +
            "1OdIs8FyfX1Cb5eOAfb/zFObnu557Nl5kAXZBoB9zgDmIzEP1g31wc8AgdvrhdYHX1coYk7DehtOAGQK" +
            "fcs7Fhd3YHmWN2sASr4oN4r0VOz3SWaSJvQUEjEkZCN08+Hq+JD0JJFJDbvJ4MQ+RBaguilTAfoDY+az" +
            "VwGqBJ9TOX40HTneS3KR2QnUcdtqkSux8Vxl2/iuJJWQnVn5pEGhQ6wW4HRuVbbvY+bNdWNeUFs/zi4n" +
            "5wCLCBfTqHSLz6JsHOXugUz1/Pwycj+paJ9OFWNa76QY9gfwQ21t4N+/6l1j1udD7s37nu96PWIxVHsI" +
            "hogzcl0V3SRd57MO+TnfgqDk50ru9l3eIXQrMy5F2jSeNPw/3/GLP+WWe8zVYIrv/12O/xlzwpltTYLr" +
            "5IfP3ljvX1gPzfPXIl64QuO9lHrnbNx/mY+ME2TKI1DtDVTfs/8s8ZxYioj3SQQ4BygrPXqFuQR9Clnv" +
            "M6UOoXOBr5TWea/kExcWe88t85cr1DL/QuDxPuvoc9yzIc917LPTl71cy/M+o9qQ9tZd0YYToZU77uH8" +
            "XIkT3Vt7lCjXOO12QJ00PLuQjRa6Gr3cyPjUHgap9L/VU7SaV9/w8jY9Ac3I0mLch5/donJ7p8xHIW4d" +
            "5vpdc4zmf6+NYniMPf33d9DW+80EJVOMpm9u2+QjkbyeX3AuzzmuW9pWXOH0RqMb3wvyHfYHdBJqf9bD" +
            "sSnsLsjRPgwYlkLdhqvO8AO/XNs/3jOU58vI2sL+n8V7z189/5HqB3t55mS+9v8cPQiDv8/z/+9vJbe/" +
            "sntG+Q2/bzglCoNwykOparJo+F6vC+aX8GmAZItXO/1556Hlf2ofplpuCjNW9wVuenXnSeMv0cI4y9YZ" +
            "cdciVr4t5WFloMfnNH2HL0heWYNtgHtkKkBc1dMtaz9OzzbxlCPSOeheiVZ9HdRGqU1EVrM3BfVg13YK" +
            "lVxDMpVK6Ba7OcS0MClFbexNO85Eu33Xv/946uAL0Mixx8gnavdW7r7L0hZ10a8P51O5C309g9CSQlbY" +
            "VkZ672akuIVt1dwu2Nsc5L9wGLKSgYbUSP3ojWV9E9pfBm97N12tsfR7bU3+Q3Ea33uodx0fl9kI15CZ" +
            "xoe8nMHL1QG73XYPIMsewaCEyh247EHQ3jLeA/i5+nqeA+bprbwXiIpB3GPJ3y31107nq4GJtjnMfxH5" +
            "YD5P7ZUQpSyHw9kK52m8t2eYXfxm9ZXDfUWHGyRwCtFcg7utwNaFqzdZU8mlhbnq/kLsgT/p8QrR/Dii" +
            "XEJpPC/NqHb1pYd4y5dLCcgn1fo0tlxDbW33DCNH5NOEwWthSnyLV/R7suepCtTB/I+c6FvjsQPP6SO+" +
            "3SeQjalwE8pPUe/RlB8pnZ/JqYIV8aF5tLp+dLIodyH/dXyZ/m/emWS/vQZCe9rAC7UDaZVBcnONBCxX" +
            "m5ZmNr9Ge5FuqPdVob4XrfXl7Gzoqgfwfwxrnmd565SLQfO1JqFNz5J2r/N6ewF+eeZptQlis2R9eVAL" +
            "5e7pcs/HzfWWoz0UMjyqf3XMWTKBCj94rvCcdwd0g3g5HxPc/GFY3zKPvei4jv4o8mDCf7jLvCeWNjIG" +
            "OzlEo3AnDavZAD4C3MwZDDxQEC4jPGFkMLMF6dAgBXET2ZEQnUF96SF9HNr5O9wtwj6l021GqiW86xI9" +
            "FDMTLj9p+8bZ/YOwJPdBa4A+e/709ULF9ioKmzycD5c/H+uP0lJdEahBZ6pkZWIbIHETWdJ0bBNgTZKA" +
            "asicJ/ROdYbGMbKttNd1ky9UDBU0f7LkiYKeKXLdifzrXGW1QYbD1QH5vRsX2Mu7UwlriIxB0B7Lyzl/" +
            "lm9EOkz5sPgvoJs8fsBPZI7F1H1Qy4GAjUG9Yi11NERcW0U1Gbw+Sby4uaPooz3XJtBN31YVq99+DCHs" +
            "Kgc4nW5iOA4X4FEVJHy4fO3y5vczzDnEsrH96/CswImCwEcjVwqaSPXM/n/i77qAvIq4X11c+ffVoewl" +
            "UANzhym2sOWRrU30hLpeQgUBUgvUrBiuBwHbvXpnnVHqfHiiGT1H/ww5T7rA1x+M27A5vg6pug5lAYGU" +
            "e79TFQrKJ4pWJXHL5nd72RLh2r25TgSXS0oEqUD4MdgJBtlN/Ndl+v145yTUBLO+nchUTi+juhU51jIb" +
            "12PpHEeBjx55AIMhWX+fTPZ2xxLnmbdRFxKvu9z/sMDaXbAv8EufcoCJQ9PhAkUswAKvJBxOCtr9d7FA" +
            "D7ER1wGNo7yk90DsLIss9c2CLPefn0y1ER11PFgv29kADjVztnz8+kxdzUY3TsBoK/wfTKEIZCczzEgA" +
            "AAABJRU5ErkJggg==")]
        public string SoundPadNotRunning {
            get {
                return ((string)(this["SoundPadNotRunning"]));
            }
        }
    }
}
